#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="pxe"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"
        SERVICE_XPATH_ENTRY="${SERVICE_XPATH}/entries/entry"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_node "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_key "${SERVICE_XPATH}" "sharedfolderref" ""
            omv_config_add_key "${SERVICE_XPATH}" "enableWinPath" "0"
            omv_config_add_node "${SERVICE_XPATH}" "entries"
        fi

        if dpkg --compare-versions "${2}" lt-nl "3.2"; then

            count=$(omv_config_get_count "${SERVICE_XPATH_ENTRY}");
            index=1;
            while [ ${index} -le ${count} ]; do
                if omv_config_exists "${SERVICE_XPATH_ENTRY}[position()=${index}]/group"; then
                    omv_config_rename "${SERVICE_XPATH_ENTRY}[position()=${index}]/group" "grp"
                fi
                index=$(( ${index} + 1 ))
            done;

        fi

        if dpkg --compare-versions "${2}" lt-nl "3.11"; then
            omv_config_add_key "${SERVICE_XPATH}" "port" "8001"
        fi
        
        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
